//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPORTEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assignments()
        {
            this.computers = new HashSet<computers>();
            this.devices = new HashSet<devices>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int deviceType_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public Nullable<int> computer_id { get; set; }
        public int state_id { get; set; }
        public int proyect_id { get; set; }
        public int responsibleA_id { get; set; }
        public int responsibleR_id { get; set; }
        public System.DateTime date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<computers> computers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<devices> devices { get; set; }
        public virtual deviceTypes deviceTypes { get; set; }
        public virtual proyects proyects { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual states states { get; set; }
        public virtual users users2 { get; set; }
    }
}
