//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignments()
        {
            this.Devices = new HashSet<Devices>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int device_type_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public int state_id { get; set; }
        public int proyect_id { get; set; }
        public string responsive_number { get; set; }
        public int responsible_up_id { get; set; }
        public Nullable<int> responsible_down_id { get; set; }
        public int ticket_number_up { get; set; }
        public Nullable<int> ticket_number_down { get; set; }
        public System.DateTime create_at { get; set; }
        public Nullable<System.DateTime> edit_at { get; set; }
    
        public virtual App_Users App_Users { get; set; }
        public virtual App_Users App_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devices> Devices { get; set; }
        public virtual Device_Types Device_Types { get; set; }
        public virtual Proyects Proyects { get; set; }
        public virtual States States { get; set; }
        public virtual Users Users { get; set; }
    }
}
