//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int id { get; set; }
        public int device_type_id { get; set; }
        public int brand_id { get; set; }
        public int model_id { get; set; }
        public int location_id { get; set; }
        public int state_id { get; set; }
        public string serial_number { get; set; }
        public string stock_number { get; set; }
        public Nullable<int> assignment_id { get; set; }
        public int proyect_id { get; set; }
        public System.DateTime create_at { get; set; }
        public string comments { get; set; }
        public int responsible_id { get; set; }
        public Nullable<int> computer_extra_id { get; set; }
    
        public virtual App_Users App_Users { get; set; }
        public virtual Assignments Assignments { get; set; }
        public virtual Brands Brands { get; set; }
        public virtual Computer_Extras Computer_Extras { get; set; }
        public virtual Device_Types Device_Types { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Models Models { get; set; }
        public virtual Proyects Proyects { get; set; }
        public virtual States States { get; set; }
    }
}
