//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemInventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventoryContext : DbContext
    {
        public inventoryContext()
            : base("name=inventoryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App_Users> App_Users { get; set; }
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Computer_Extras> Computer_Extras { get; set; }
        public virtual DbSet<Device_Types> Device_Types { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Operating_Systems> Operating_Systems { get; set; }
        public virtual DbSet<Processors> Processors { get; set; }
        public virtual DbSet<Proyects> Proyects { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<Titles> Titles { get; set; }
        public virtual DbSet<User_Types> User_Types { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
